name: Linux Integration Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build package corerad test binary
      run: go test -c -race ./internal/corerad/

    - name: Run package corerad integration tests
      run: sudo ./corerad.test -test.run TestAdvertiser

    - name: Build package system test binary
      run: go test -c -race ./internal/system/

    - name: Run package system integration tests
      run: sudo ./system.test
