name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download staticcheck
      run: go get honnef.co/go/tools/cmd/staticcheck

    - name: Print staticcheck version
      run: go run honnef.co/go/tools/cmd/staticcheck -version

    - name: Run staticcheck
      run: go run honnef.co/go/tools/cmd/staticcheck -- ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run CI script
      run: ./scripts/cibuild.sh

    - name: Build CoreRAD
      run: go build ./cmd/corerad/

    - name: Generate default TOML configuration
      run: ./corerad -init

    - name: Verify default TOML configuration
      run: go run github.com/BurntSushi/toml/cmd/tomlv -- ./corerad.toml
